### ISSUE TITLE
dledger

### ISSUE THREAD

**Issue by wangwj** [openmessaging/openmessaging-storage-dledger#1]
@dongeforever  这个项目是要写一个简单实现我们这个协议的例子吗，还是有其他的考量，最近想在研究https://github.com/atomix/atomix 用openmessaging封装下，实现一个简单的事件驱动服务，初步发现思路好想一样。

**Comment by dongeforever** [comment]
@wangwj dledger的目标是基于raft实现强一致高可用的顺序commitlog存储引擎。
提供顺序存储commitlog的功能，其定位是一个library，方便嵌入各个系统中。主要应用有以下：
1.作为消息存储，直接存取，例如对接RocketMQ，替换原有的Commitlog；
2.作为操作日志，类似于Mysql的binlog，与RocksDB等配合，可以实现一个高可用的嵌入式KV
