### ISSUE TITLE
Term of leader is -1 when there is just one server

### ISSUE THREAD

**Issue by husterxsp** [openmessaging/openmessaging-storage-dledger#15]
Initially, `currTerm` is -1 and `lastParseResult` is WAIT_TO_REVOTE.
When there is just one server, after election, the server is leader but the term is still -1, and it looks weird. So I think the the initial value of `currTerm` should be 0. 
And according to the raft paper, currentTerm is also 
> initialized to 0 on first boot, increases monotonically

**Comment by dongeforever** [comment]
@husterxsp It makes sense. Maybe submit a PR to polish it is a good choice.
