### ISSUE TITLE
Hope to be involved in the dledger project

### ISSUE THREAD

**Issue by manijndl** [openmessaging/openmessaging-storage-dledger#3]
Hi is there any enhancement feature do u have? i would like to contribute in this project

**Comment by dongeforever** [comment]
@manijndl
There are a lot of features in the roadmap: 
1. Preferred Leader Election
2. Mirror one group in a data center to another group in another data center 
3. Manually Configured Leader
4. Automatically Degenerated to Master Slave Architecture

Specifically,  the first one "preferred leader election" has an important impact on failover when dledger is deployed in more than one data centers.

Any contribution is welcome. And it will be nice to write some design doc firstly if you want to contribute a big feature rather other trivial changes.

**Comment by aleafboat** [comment]
nice
