### ISSUE TITLE
volatile needIncreaseTermImmediately

### ISSUE THREAD

**Issue by luoxn28** [openmessaging/openmessaging-storage-dledger#30]
你好，`io.openmessaging.storage.dledger.DLedgerLeaderElector`中属性`needIncreaseTermImmediately`最好是设置成volatile类型，保证多线程间内存可见性。
```java
private boolean needIncreaseTermImmediately = false;
```

**Comment by RongtongJin** [comment]
IMO, it's necessary. You can submit a PR to polish relate code.

**Comment by shibd** [comment]
我可以提PR修复这个问题吗？是否需要对其他类的成员的可见性也做下修改。

**Comment by RongtongJin** [comment]
> 我可以提PR修复这个问题吗？是否需要对其他类的成员的可见性也做下修改。

Of course, any enhancements are welcomed.
