### ISSUE TITLE
Bug with ledgerEndTerm

### ISSUE THREAD

**Issue by TerrellChen** [openmessaging/openmessaging-storage-dledger#52]
Mostly, ledgerEndTerm is assigned in two ways:
1. recovery from log
2. appendAsFollow or appendAsLeader
For the first way, if there is no writing, ledgerEndTerm value is generated from file which is decided by log. And for the second way, the value is generated from memberState.currTerm, which could be increased by election, greater then log. They are different.

Think about a cluster with node a, b, c. 
Node a has complete data, as leader. 
Node b has complete data but has just been restarted, as follower. 
Node c has poor data, and is synchronizing from a for now.

The ledgerEndTerm on node c could a value greater than log's term, caused by past election.
The ledgerEndTerm on node b is the value equals log's term.

The node c with poor data will become leader, if we shutdown node a.
HandleVote method only compare ledgerEndIndex when ledgerEndTerm is equal. On this situation, ledgerEndTerm on node b is less than node c, so node b will accept the voteRequest from node c.

What does ledgerEndTerm for? 
What's the reason to make ledgerEndTerm = memberState.currTerm()? 
Can we let ledgerEndTerm = entry.term?

**Comment by RongtongJin** [comment]
IMO, it is indeed a bug. Could you submit a pr to solve this issue？

**Comment by TerrellChen** [comment]
@RongtongJin #53

**Comment by RongtongJin** [comment]
Merged
