### ISSUE TITLE
[Question about a possible reversed priority case and prevoting process]

### ISSUE THREAD

**Issue by imaffe** [openmessaging/openmessaging-storage-dledger#58]
I was reading the raft implementation recently, and learned a lot from it. I met some problems which are very likely I understood something wrong. Would appreciate it if someone can help with my process.

Supposing a very normal 4-node cluster, with maxHeartBreakLeak: node 0 < 1 < 2 < 3

1. initial state

| node  | currVotedFor | currTerm | role      | lastParseResult |
|-------|--------------|----------|-----------| ----------- |       
| node0 | node0         | 1        | leader      |  PASS     |
| node1 | node0        | 1        | follower |  WAIT_TO_REVOTE   |
| node2 | node0         | 1        | follower |  WAIT_TO_REVOTE    |
| node3 | node0         | 1        | follower |  WAIT_TO_REVOTE   |

2. and node 0 goes down

| node  | currVotedFor | currTerm | role      | lastParseResult |
|-------|--------------|----------|-----------| -- |       
| node1 | node0        | 1        | follower |  WAIT_TO_REVOTE   |
| node2 | node0         | 1        | follower |  WAIT_TO_REVOTE    |
| node3 | node0         | 1        | follower |  WAIT_TO_REVOTE   |

3. node 1 timeout first, become a candidate. issues a vote request with term 1 (hasn't increase term yet), but it will be refused because node 2, 3 still believes there is a leader, so they would return REJECT_ALREADY_HAS_LEADER and do nothing.   node 1 upon receiving these responses would reset timer, and stay in WAIT_TO_REVOTE  state. Same thing happens to node2. after node 2 received REJECT_ALREADY_HAS_LEADER responses, the state would be 

| node  | currVotedFor | currTerm | role      | lastParseResult |
|-------|--------------|----------|-----------| -- |       
| node1 | node1        | 1        | candidate |  WAIT_TO_REVOTE   |
| node2 | node2        | 1        | candidate |  WAIT_TO_REVOTE    |
| node3 | node0         | 1        | follower |  WAIT_TO_REVOTE   |

4. This way, only when node 3 timeout lastly it would request votes without getting any  REJECT_ALREADY_HAS_LEADER response, and continue to WAIT_TO_VOTE_NEXT state. 
From the time it received 2 REJECT_ALREADY_VOTED( because node 1, 2 all voted for themselves). it would start a timer : lastVotedTime + random value between 300ms and 1000 ms (this value can be changed). Since this is a random value, it might be that node 3 eventually has the smallest timeout interval, and after the smallest timer expires,it increase its term and force node 1 and node 2 to increase their term too (set their needIncreaseTermImmediately). This way node 3 will be the final leader, which reversed the priority order.

This can be mitigated by giving node 3 a much larger timeout interval, but still we might look for something better..

Some thoughts: In raft we would usually first increase term and request vote, here node 1 requests votes without increase its term and I suppose this  is implementing the pre-vote algorithm mentioned in the paper. 

IMHO, pre-vote is for a potential candidate(like node1) to check if it is possible to pass the election(more up-to-date than a majority of nodes) before increasing term. In our current implementation, node 1 first requests votes with term 1, and other followers with same term would return REJECT_ALREADY_HAS_LEADER. In this case other followers didn't check if the incoming vote request is more up-to-date than followers themselves. If we can somehow subdivide the REJECT_ALREADY_HAS_LEADER response to something like

- REJECT_ALREADY_HAS_LEADER_PREVOTE_ACCEPT
- REJECT_ALREADY_HAS_LEADER_PREVOTE_REJECT

then node1 receives enough prevote_accept, it can increase its term and start a revote immediately. Otherwise it just remains in WAIT_TO_REVOTE  process.

p.s. Actually I didn't find how the pre-vote was implemented in Dledger, wondering if there are some pre-vote design documentations? Thanks if anyone can give me some hints on pre-vote implementation in Dledger.

**Comment by single-wolf** [comment]
pre-vote is necessary to void unavailability in some corner, e.g Symmetric network partition tolerance. (unfortunately this feature not be implemented in Dledger)
IMHO : 
**step 3** : node 1 upon receiving REJECT_ALREADY_HAS_LEADER responses would reset timer that for next pre-vote, and stay in follower role(not increase term yet).
**step 4** : node2 would request pre-votes after timeout and get ACCEPT response from  a majority of nodes (self and node1), in this way, node2 will be the first to become candidate and leader role.

Only the node ,that get pre-vote ACCEPT response from  a majority of nodes ,could  become candidate, and the node should undoubtedly refuse the pre-vote requests while still believes there is a leader because the request node is more suspicious.

p.s. I was also reading some raft implementation recently,  the sofa-jraft project seems implement 
it more clearly. XD

**Comment by lixinwen** [comment]
@imaffe 
What is the priority order you mentioned? is it defined by maxHeartbeatLead?

**Comment by imaffe** [comment]
> @imaffe
> What is the priority order you mentioned? is it defined by maxHeartbeatLead?

Yes, different maxmaxHeartbeatLeak decides how long before each follower timeout to a candidate, thus determine their priorities in becoming candidates

**Comment by imaffe** [comment]
> Only the node ,that get pre-vote ACCEPT response from a majority of nodes ,could become candidate, and the node should undoubtedly refuse the pre-vote requests while still believes there is a leader because the request node is more suspicious.

When I was reading the code, if a node receives a majority of ACCEPT, it would become leader directly, and this is where I found it weird (and this is where leads me to doubt that it's not implementing pre-vote)

But It's been a while since I last touch this codebase, I might be wrong. I'll check again probably within next days ~ Thanks for your comment and really appreciate it we can discuss this topic ~

**Comment by lixinwen** [comment]
@imaffe 
Dledger does not say that the priority is determined by maxHeartbeatLeak.
I think the priority should be specified by additional parameters, Can specify a node or a machine-room as a prefered-leader. Just personal thoughts.
Maybe has implemented in perfered-leader branch, But i haven't seen the code of this branch.

**Comment by imaffe** [comment]
> @imaffe
> Dledger does not say that the priority is determined by maxHeartbeatLeak.
> I think the priority should be specified by additional parameters, Can specify a node or a machine-room as a prefered-leader. Just personal thoughts.
> Maybe has implemented in perfered-leader branch, But i haven't seen the code of this branch.

Dledger support explicit preferred-leader by explicitly hand off leadership. And the problem I described still exists even when explicit priorities are assigned (I just used maxHeartbeatLeak for example ): the major problem is, a candidate has to wait for every follower become candidate before it can proceed, and I very doubt this is the expected behaviour.
