### ISSUE TITLE
[BUG] Leader doesn't push entries to follower

### ISSUE THREAD

**Issue by lixinwen** [openmessaging/openmessaging-storage-dledger#61]
step1：Leader and follower is consistent.
step2：Shutdown follower, Delete all data, Simulated data loss.
step3：Restart follower. At this time, When leader has no new write,  then existing data will not be push. 

Because EntryDispatcher#doAppend always run the following code：
if (writeIndex > dLedgerStore.getLedgerEndIndex()) {
                    doCommit();
                    doCheckAppendResponse();
                    break;
                }

I think re-compare should be triggered at this time, Triggered by doCommit response or exception.

**Comment by TerrellChen** [comment]
https://github.com/openmessaging/openmessaging-storage-dledger/pull/50
