### ISSUE TITLE
[RMQ-ISSUE-690][Feature] support Batch Entry Append

### ISSUE THREAD

**Issue by TerrellChen** [openmessaging/openmessaging-storage-dledger#64]
RocketMQ doesn't implement putMessages in DLedgerCommitLog.
It could be easier to implement putMessages with DLedger supporting Batch Entry Appending.

**Comment by TerrellChen** [comment]
@RongtongJin Hi, could you pls review this pr?
It would be nice if you release a stable version for this, so that the https://github.com/apache/rocketmq/issues/690 can be implemented.

**Comment by RongtongJin** [comment]
> @RongtongJin Hi, could you pls review this pr?
> It would be nice if you release a stable version for this, so that the [apache/rocketmq#690](https://github.com/apache/rocketmq/issues/690) can be implemented.

OK, I will review it ASAP
