### ISSUE TITLE
Polish leader election process when in network partition case

### ISSUE THREAD

**Issue by jacky1193610322** [openmessaging/openmessaging-storage-dledger#7]
类似于raft的prevote要解决的问题，在检测到有leader的数目 + !validNum > Quorum时候，是不是可以先不增加term，因为增加term是在有可能获得大部分的选票，这样才有意义。

**Comment by dongeforever** [comment]
@jacky1193610322 代码里有相应的设计哈，看下DLedgerLeaderElector的WAIT_TO_VOTE_NEXT和WAIT_TO_REVOTE的区别

**Comment by jacky1193610322** [comment]
谢谢东哥回复，东哥我看了两者的区别，我看了底下的有一个判断逻辑
![image](https://user-images.githubusercontent.com/16514353/52992291-0bff8f00-344b-11e9-9ba1-c03b2bdc56a7.png)
这里只要检测到有leader的存在那么，就会增大等待时间，但是还是会在下一次循环中增加term，我的意思是当对有leader的个数也进行统计，当有leader的个数加上invalidNum(网络不通) 大于 Quorum的时候，不进行累加term，因为累加了也获得不了leader，当有leader的个数大于Quorum的时候，也不累加，这样可以防止有一个与leader失联时候的节点造成扰动，因为dleader发起投票的时候已经返回了相应的值，这个值完全可以作为prevote了。

**Comment by jacky1193610322** [comment]
> 谢谢东哥回复，东哥我看了两者的区别，我看了底下的有一个判断逻辑
> ![image](https://user-images.githubusercontent.com/16514353/52992291-0bff8f00-344b-11e9-9ba1-c03b2bdc56a7.png)
> 这里只要检测到有leader的存在那么，就会增大等待时间，但是还是会在下一次循环中增加term，我的意思是对有leader的个数也进行统计，当有leader的个数加上invalidNum(网络不通) 大于 Quorum的时候，不进行累加term，因为累加了也获得不了leader，当有leader的个数大于Quorum的时候，也不累加，这样可以防止有一个与leader失联时候的节点造成扰动，因为dleader发起投票的时候已经返回了相应的值，这个值完全可以作为prevote了。

**Comment by vongosling** [comment]
@jacky1193610322 pre-vote protocol has been added. Welcome to have a try :-)
