### ISSUE TITLE
Out of memory error when dledger is used

### ISSUE THREAD

**Issue by LuciferInLove** [openmessaging/openmessaging-storage-dledger#77]
Hello. We had the rocketmq cluster installed with master-slave architecture, and then we moved it to new dledger architecture. Brokers are running on small ec2 instances with such java options:
```
-Xms128m -Xmx128m -Xmn128m -XX:G1HeapRegionSize=1m -XX:MaxDirectMemorySize=256m
```

When we've used master-slave architecture all worked correctly, but when we moved to the dledger architecture we became to get Out of memory errors. We see many threads that allocate 4mb buffer. Is it the right behavior?

The log file with errors is attached.
[hs_err_pid_1.log](https://github.com/openmessaging/openmessaging-storage-dledger/files/5511168/hs_err_pid_1.log)

**Comment by vongosling** [comment]
You could raise a question in https://github.com/apache/rocketmq/issues

**Comment by LuciferInLove** [comment]
@vongosling, thanks.
